.build-tests-base:
  stage: build
  image: ubuntu:18.04
  before_script:
    - apt-get update -y
    - apt-get install --no-install-recommends -y ${EIGEN_CI_CXX_COMPILER} ${EIGEN_CI_CC_COMPILER} cmake ninja-build
  script:
    - mkdir -p ${BUILDDIR} && cd ${BUILDDIR}
    - echo "CXX=${EIGEN_CI_CXX_COMPILER} CC=${EIGEN_CI_CC_COMPILER} cmake -G ${EIGEN_CI_CMAKE_GENEATOR} -DEIGEN_SPLIT_TESTSUITE=${EIGEN_CI_TESTSUITE_SIZE} -DEIGEN_TEST_CXX11=${EIGEN_TEST_CXX11} ${EIGEN_CI_CXX_FLAGS}"
    - CXX=${EIGEN_CI_CXX_COMPILER} CC=${EIGEN_CI_CC_COMPILER} cmake -G ${EIGEN_CI_CMAKE_GENEATOR} -DEIGEN_SPLIT_TESTSUITE=${EIGEN_CI_TESTSUITE_SIZE} -DEIGEN_TEST_CXX11=${EIGEN_TEST_CXX11} ${EIGEN_CI_CXX_FLAGS} ..
    - cmake --build . --target buildtestspart${EIGEN_CI_TESTSUITE_PART}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ${BUILDDIR}/
    expire_in: 5 days

# GCC 4.8
# This is the oldest GCC version we support
build-tests-g++-4.8-cxx11:
  extends: .build-tests-base
  variables:
    EIGEN_CI_CXX_COMPILER: "g++-4.8"
    EIGEN_CI_CC_COMPILER: "gcc-4.8"
  parallel:
    matrix:
      - EIGEN_CI_TESTSUITE_PART: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        EIGEN_TEST_CXX11: "On"

build-tests-g++-4.8-cxx03:
  extends: .build-tests-base
  variables:
    EIGEN_CI_CXX_COMPILER: "g++-4.8"
    EIGEN_CI_CC_COMPILER: "gcc-4.8"
  parallel:
    matrix:
      - EIGEN_CI_TESTSUITE_PART: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        EIGEN_TEST_CXX11: "Off"
