.run_tests:
  allow_failure: true
  stage: test
  image: ubuntu:18.04
  before_script:
    - apt-get update -y
    - apt-get install --no-install-recommends -y cmake ninja-build xsltproc
  script:
    - echo "cd ${BUILDDIR} && ctest --output-on-failure"
    - cd ${BUILDDIR} && ctest --output-on-failure --no-compress-output --build-no-clean -T test
    - xsltproc ../ci/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > "JUnitTestResults_$CI_JOB_ID.xml"
  artifacts:
    reports:
      junit:
        - "build/JUnitTestResults_$CI_JOB_ID.xml"
    expire_in: 5 days

# GCC 4.8
run-tests-g++-4.8-cxx11-on:
  only:
    - schedules
  extends: .run_tests
  dependencies:
    - build-tests-g++-4.8-cxx11-on

run-tests-g++-4.8-cxx11-off:
  only:
    - schedules
  extends: .run_tests
  dependencies:
    - build-tests-g++-4.8-cxx11-off

# GCC 10
run-tests-g++-10-cxx11-on:
  extends: .run_tests
  dependencies:
    - build-tests-g++-10-cxx11-on

run-tests-g++-10-cxx11-off:
  extends: .run_tests
  dependencies:
    - build-tests-g++-10-cxx11-off

